baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Infrastructure Coders'

[params]
  [params.docs]
    title = "Infrastructure Coders"
    themeColor = "cyan"        # set theme color (e.g., "blue", "red", "green")
    darkMode = true               # enable dark mode support
    prismTheme = "twilight"            # set Prism.js theme (e.g., "okaidia", "twilight", "solarizedlight")

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false